version: '3.9'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: tech-challenge-01
    volumes:
      - .:/app
    ports:
      - "3000:8000"
    environment:
      DATABASE_URL: postgres://postgres:postgres@db:5432/web_scrapping
      APP_NAME: "Tech Challenge 01"
      URL_TO_SCRAP: https://books.toscrape.com/
      SECRET_KEY: 3f3c9b2b-5c5e-4c5e-8c5e-5c5e4c5e5c5e
      API_PREFIX: /api/v1
      ACCESS_TOKEN_EXPIRE_MINUTES: 120
      REFRESH_TOKEN_EXPIRE_DAYS: 30
      ALGORITHM: HS256
  db:
    image: postgres:16
    container_name: db_postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: web_scrapping
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
volumes:
  postgres_data:
